name: Test suite

on: [push, pull_request]

jobs:


  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: python ./scripts/bz.py
      shell: cmd

  
